export const EstadoSolicitudCreditoConstants = {
    //PENDIENTE: 41,
    //RECHAZADO: 42,
    REGISTROENPROCESO: 41,
    REGISTROCANCELADO: 42,
    SUBASTAENPROCESO: 55,
    SUBSTACANCELADA: 62,
    PRESTAMOENPROCESO: 63,
    PRESTAMOCANCELADO: 64,
    PRESTAMOAPROBADO: 65
};
