export const ParametroConstants = {
  PAIS: 0,
  SEXO: 1,
  GRADOINSTRUCCION: 2,
  DESTINOCREDITO: 3,
  TIPODOCUMENTO: 4,
  ESTADOCIVIL: 5,
  TIPOACTIVIDAD: 6,
  RUBROACTIVIDAD: 7,
  TIPOCUENTA: 8,
  BANCOS: 9,
  ESTADOSOLICITUDCREDITO: 55
};
