export const ParametroConstants = {
  PAIS: 0,
  SEXO: 1,
  GRADOINSTRUCCION: 4,
  DESTINOCREDITO: 10,
  TIPODOCUMENTO: 13,
  ESTADOCIVIL: 16,
  TIPOACTIVIDAD: 23,
  RUBROACTIVIDAD: 26,
  TIPOCUENTA: 29,
  BANCOS: 32,
  SEGURO: 37
};
